Fs 01
PavelRadzevich/finalsurge pull request #1
Opened 2023-04-30 19:19 UTC by PavelRadzevich

From under IDEA tests are launched, from under maven are not present.

2023-05-01 20:30 UTC, testershmester requested changes

2023-05-01 20:30 UTC, testershmester commented on src/main/java/by/teachmeskills/page/CalendarPage.java
> +
- не нужны лишние строки

2023-05-01 20:30 UTC, testershmester commented on src/main/java/by/teachmeskills/page/LoginPage.java
> +        log.info("URL : {}", url().toString());
url() опустить ниже open()
 url() итак возвращает строку, .toString() не нужен

2023-05-01 20:30 UTC, testershmester commented on src/main/java/by/teachmeskills/util/testng/TestListener.java
> +
-

2023-05-01 20:30 UTC, testershmester commented on src/test/java/by/teachmeskills/LoginPageTest.java
> +                .shouldBe(Condition.visible
можно использовать статический импорт и будет форматирование выглядеть лучше
                .shouldBe(visible.because("no error message"))

2023-05-01 20:30 UTC, testershmester commented on src/test/java/by/teachmeskills/LoginPageTest.java
> +                .shouldHave(Condition.text("Please enter your e-mail address.")
проверки лучше делать асертами в тестах, особенно если есть api часть еще

2023-05-01 20:30 UTC, testershmester commented on src/test/java/by/teachmeskills/UserProfilePageTest.java
> +        userProfile.profileNameFld
с филдами в джава принято работать через геттеры сеттеры

2023-05-01 21:42 UTC, PavelRadzevich commented on src/main/java/by/teachmeskills/page/LoginPage.java
> +        log.info("URL : {}", url().toString());
Corrected.

2023-05-01 21:46 UTC, PavelRadzevich commented on src/main/java/by/teachmeskills/page/CalendarPage.java
> +
Corrected.

2023-05-01 21:49 UTC, PavelRadzevich commented on src/main/java/by/teachmeskills/util/testng/TestListener.java
> +
Corrected.

2023-05-01 21:58 UTC, PavelRadzevich commented on src/test/java/by/teachmeskills/LoginPageTest.java
> +                .shouldBe(Condition.visible
Corrected.

2023-05-01 22:00 UTC, PavelRadzevich commented on src/test/java/by/teachmeskills/LoginPageTest.java
> +                .shouldHave(Condition.text("Please enter your e-mail address.")
Функционала Selenide для проверки условий в данном случае достаточно.

2023-05-01 22:07 UTC, PavelRadzevich commented on src/test/java/by/teachmeskills/UserProfilePageTest.java
> +        userProfile.profileNameFld
А разве метод setUserFirstName("First") не является таковым?

2023-05-03 10:07 UTC, testershmester approved these changes

2023-05-05 23:10 UTC, merged